### ISSUE TITLE
Allow option to change zoom level and placement

### ISSUE THREAD

**Issue by jalperin** [vasturiano/cartogram-chart#1]
I am having a hard time placing the map generated by this in a page. Although I can change the size of the object with the width and height methods, the map remains at the same Zoom level and position, which is including a lot of white space on the left and cutting off parts of the world.

**Comment by vasturiano** [comment]
@jalperin thanks for reaching out. You can control the map translation and zoom using the projection itself (set by the `projection()` method).

This is the code for the default projection:
https://github.com/vasturiano/cartogram-chart/blob/master/src/cartogram.js#L18

As documented, it defaults to:

> geoMercator (centered on prime meridian, slightly tilted towards the northern hemisphere)

If you wish to change the zoom/scale for example, you can just do:
```
myChart.projection().scale(6)
```

You can also use the above method to use a different [projection](https://github.com/d3/d3-geo-projection) other than `geoMercator`.

**Comment by jalperin** [comment]
small correction to the above, I think. This is what it needs to look like: 

`.projection(d3.geoEquirectangular().scale(200))`

**Comment by vasturiano** [comment]
@jalperin that's only if you need to change the projection. If you just want to change the scale then the previous code should suffice.

**Comment by jalperin** [comment]
I was getting the following error: 

```
(index):173 Uncaught TypeError: Cartogram(...).topoJson(...).projection(...).scale(...).topoObjectName is not a function
    at update ((index):173)
    at <anonymous>:1:1
```
