### ISSUE TITLE
Wrong position for tooltip

### ISSUE THREAD

**Issue by pvictor** [vasturiano/cartogram-chart#12]
Hello,

With version > v1.1.3 , the tooltip is not positioned correctly if there are elements above the cartogram.
In examples, you can add `<div style="height: 400px;"></div>` above the div rendering the cartogram to see this behavior.

![image](https://user-images.githubusercontent.com/4415580/140894072-6caf90d9-1f9f-480e-8bd3-b77965d3557e.png)

Thanks!

**Comment by vasturiano** [comment]
Thanks for the report @pvictor. 👍 
This is now fixed in the latest version (`1.2.3`).
